# Generated by Django 6.0.3 on 2026-03-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipobiomedico',
            name='hoja_vida_vida',
            field=models.FileField(blank=True, null=True, upload_to='hojas_vida/'),
        ),
        migrations.AddField(
            model_name='equipobiomedico',
            name='qr_codigo',
            field=models.ImageField(blank=True, null=True, upload_to='qr_equipos/'),
        ),
    ]
