# Generated by Django 6.0.1 on 2026-02-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenmantenimiento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('proceso', 'En proceso'), ('ejecutada', 'Ejecutada'), ('aprobada', 'Aprobada')], default='pendiente', max_length=20),
        ),
    ]
