# Generated by Django 6.0.1 on 2026-02-21 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0006_alter_ordenmantenimiento_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenmantenimiento',
            options={'permissions': [('puede_finalizar_orden', 'Puede finalizar_orden'), ('puede_aprobar_orden', 'Puede aprobar orden'), ('puede_ver_dashboard', 'Puede ver dashboard')]},
        ),
    ]
